CREATE TABLE IF NOT EXISTS road_damage (
  street INT UNSIGNED NOT NULL,
  damage FLOAT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (street)
);